flowchart TD
    A[Inicio de Tapatapp] --> B[Login]
    B --> C{Verificar credenciales}
    C -->|Correctas| D[Acceso a la página principal]
    C -->|Incorrectas| E[Mostrar mensaje de error]
    G --> B
    D --> F[lista niños]
    E --> G[Registro]
     